### ISSUE TITLE
Can't set variable in ingresses

### ISSUE THREAD

**Issue by AlexGluck** [nixys/nxs-universal-chart#15]
Здравствуйте, вынес домен в отдельную переменную, в деплоймент подключил корректно, а в ингрес не выходит.
Что я делаю не так?

```yaml
defaultURL: "api.dev2.somedomain.ru"

deployments:
  someApi:
    replicas: 1
    containers:
    - name: some-api
      ports:
      - name: http
        containerPort: 1337
      env:
        - name: PUBLIC_URL
          value: "https://{{ .Values.defaultURL }}"

ingresses:
  someApiIngress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    hosts:
    - hostname: "{{ .Values.defaultURL }}"
      paths:
      - serviceName: some-api-svc
        servicePort: http
```

```
history.go:56: [debug] getting history for release some-api
upgrade.go:142: [debug] preparing upgrade for some-api
Error: UPGRADE FAILED: YAML parse error on universal-chart/templates/ingress.yml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.defaultURL":interface {}(nil)}
helm.go:84: [debug] error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.defaultURL":interface {}(nil)}
YAML parse error on universal-chart/templates/ingress.yml
```
