### ISSUE TITLE
Can't set a variable for image

### ISSUE THREAD

**Issue by hdclone** [nixys/nxs-universal-chart#2]
Hello.

I need to be able to set a variable in the image and imageTag fields for containers in deployment. For example like this:

```
deployments:
  deploymentname:
    containers:
    - name: containername
      image:  {{ $.Values.imageRepo }}/{{ $.Values.imageName }}
      imageTag: {{ $.Values.imageTag }}
```

And then override them when installing/upgrading the chart via `--set`:
`helm upgrade --install -f values.yaml --set imageRepo=foo --set imageName=bar --set imageTage=v2  chartname nixys/universal-chart`

That is, the output should be as follows:
```
      containers:
      - name: containername
        image: foo/bar:v2
```

**Comment by randreev1321** [comment]
Your example describes only one deployment. You can use `defaultImage` and `defaultImageTag` for such cases.

The feature you requested can be used if you want to specify docker images via the `--set` flag for multiple deployments or containers.

**Example.**

```yaml
deployments:
  app1:
    containers:
    - name: app1
      image: '{{ $.Values.imageRepo1 }}/{{ $.Values.imageApp1 }}'
      imageTag: '{{ $.Values.imageTagApp1 }}'
  ...
  app2:
    containers:
    - name: app1
      image: '{{ $.Values.imageRepo2 }}/{{ $.Values.imageApp2 }}'
      imageTag: '{{ $.Values.imageTagApp2 }}'
```

Create release with `--set` flag

```bash
helm install my-apps nixys/universal-chart -f values.yaml --set imageRepo1=reg.app.com,imageRepo2=reg.app.net,imageApp1=my-app1,imageTagApp1=v1,imageApp2=my-app2,imageTagApp2=v2
```
