### ISSUE TITLE
Affinity rules enable by default (why is not disabled?)

### ISSUE THREAD

**Issue by GRomR1** [nixys/nxs-universal-chart#21]
Is it possible don't add any affinity rules by default? I think is should be an option to enable them. By default they should be disabled. Am I right?

## How to reproduce?

Create some values file 
```yaml
# ./samples/whoami.yml
deployments:
  whoami:
    containers:
    - name: whoami
      image: containous/whoami
      imageTag: v1.5.0
```

Run generate k8s manifests with this value file
```
helm template whoami --values ./samples/whoami.yml ./ > whoami.yaml
```

The generated result was here.
```yaml

# Source: universal-chart/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-whoami
  namespace: default
  labels:
    app.kubernetes.io/name: whoami
    app.kubernetes.io/instance: whoami
    helm.sh/chart: universal-chart-2.1.0
    app.kubernetes.io/managed-by: Helm
  annotations:    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
      app.kubernetes.io/instance: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
        app.kubernetes.io/instance: whoami
      annotations:
    spec:
      affinity:       ### < ---- i think this section should not be here by default, if is not explicitly defined
        nodeAffinity:
          {}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: whoami
                  app.kubernetes.io/instance: whoami
              namespaces:
              - "default"
              topologyKey: kubernetes.io/hostname
            weight: 1
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: whoami
                  app.kubernetes.io/instance: whoami
              namespaces:
              - "default"
              topologyKey: kubernetes.io/hostname
            weight: 1
      
      containers:
      - name: whoami
        image: containous/whoami:v1.5.0
        imagePullPolicy: IfNotPresent                
        volumeMounts:
        
          []
      volumes:      
        []
```

**Comment by GRomR1** [comment]
I would like [this](https://github.com/nixys/nxs-universal-chart/blob/main/templates/deployment.yml#L47-L54) code will be like here

```yaml
      {{- if .affinity }}
      affinity: {{- include "helpers.tplvalues.render" ( dict "value" .affinity "context" $) | nindent 8 }}
      {{- else }}
      {{- if $general.enableAffinity | default false }}
      affinity:
        nodeAffinity: {{- include "helpers.affinities.nodes" (dict "type" $.Values.nodeAffinityPreset.type "key" $.Values.nodeAffinityPreset.key "values" $.Values.nodeAffinityPreset.values) | nindent 10 }}
        podAffinity: {{- include "helpers.affinities.pods" (dict "type" $.Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "helpers.affinities.pods" (dict "type" $.Values.podAntiAffinityPreset "context" $) | nindent 10 }}
      {{- end }}
      {{- end }}
```

Then [values.yaml](https://github.com/nixys/nxs-universal-chart/blob/main/values.yaml) need to add this parameters
```
deploymentsGeneral:
  enableAffinity: true # or false
```

**Comment by randreev1321** [comment]
Hi @GRomR1.

Thanks for your issue. This is good point. We'll work on this idea in the next release.

To disable the creation of affinities now, set the following values in your values file:

```yaml
podAffinityPreset: nil
podAntiAffinityPreset: nil
```

As a result, you will get an empty affinity block:

```yaml
      ...
      affinity:
        nodeAffinity:
          
        podAffinity:
          
        podAntiAffinity:
      ...
```
