### ISSUE TITLE
RBAC: ServiceAccount, Role, ClusterRole templates

### ISSUE THREAD

**Issue by GRomR1** [nixys/nxs-universal-chart#26]
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

It would be nice if chart would allow setting this via variables

**Comment by randreev1321** [comment]
Hi @GRomR1 

You have this opportunity.

If you need to extend your app by extra templates you can use `extraDeploy` option.

Here is an example how to add networkPolicy: [link](https://github.com/nixys/nxs-universal-chart#example-3)

So, you can add the templates you need similarly.

For example:

```yaml
extraDeploy:
  app-sa: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "helpers.app.fullname" (dict "name" .Values.serviceAccountName "context" $) }}
      namespace: {{ .Release.Namespace | quote }}
      labels:
        {{- include "helpers.app.labels" $ | nindent 4 }}
        {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      annotations:
        {{- with $.Values.generic.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
        {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
```
