### ISSUE TITLE
hpa sample

### ISSUE THREAD

**Issue by andrewz2010** [nixys/nxs-universal-chart#28]
Есть предложение добавить пример использования hpa.
В разных версиях кубера может меняться apiVersion, но для большинства случаев достаточно данного варианта
#example for k3s v.1.23
```
extraDeploy:
  hpa: |-
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    metadata:
      name: {{ include "helpers.app.fullname" (dict "name" "hpa" "context" $) }}
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "helpers.app.fullname" (dict "name" "api" "context" $) }}
      minReplicas: 3
      maxReplicas: 8
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 60
```

**Comment by randreev1321** [comment]
Добрый день, @andrewz2010.

Чарт уже поддерживает hpa с версии v2.0.0.

Описание доступно в [README.md](https://github.com/nixys/nxs-universal-chart#horizontalpodautoscaler-parameters).

Чтобы получить идентичный результат, вы можете использовать следующие values:

```yaml
hpas:
  hpa:
    scaleTargetRef:
      name: api
    minReplicas: 3
    maxReplicas: 8
    targetCPU: 60
    targetMemory: 60
```
