### ISSUE TITLE
Feature: use containers/initContainers definition as you wish (list or dict)

### ISSUE THREAD

**Issue by GRomR1** [nixys/nxs-universal-chart#35]
I would like to use both variants in my values. 

The first one (as it is) supports only this definition:
```yaml
deployments:
  api:
    containers:
    - name: container-name
      image: registry/image
```

But I think it is possible to use this definition too. 
```yaml
deployments:
  api:
    containers:
      container-name:
        image: registry/image
```

The function `kindIs` can help to make it (see the example [here](https://stackoverflow.com/a/71797701/4474332)). 

I can create an example and code this feature. But after this PR https://github.com/nixys/nxs-universal-chart/pull/31 was merged. Also would like to complete discussion about License (because it's limit me) -  https://github.com/nixys/nxs-universal-chart/issues/34
