### ISSUE TITLE
Feature: global envs applied to all containers

### ISSUE THREAD

**Issue by Tri0L** [nixys/nxs-universal-chart#36]
For example we have backend with migrations(hook). Both containers need the same environment variables

```
  - name: SOME_VAR
    value: "some value"
  - name: SOME_VAR_FROM_SECRET
    valueFrom:
      secretKeyRef:
        name: some_secret
        key: some_key
```

For now I need to write envs twice(for app and for migrations). Would be better to define something like `extraVolumes` but for env vars, and automaticly add it to all containers in chart.

**Comment by randreev1321** [comment]
Hi, @Tri0L.

Nice idea, we will consider your proposal and try to propose a solution.

**Comment by randreev1321** [comment]
Hi, @Tri0L.

As you ask we added functionality to have ability setup general envs for workloads.

Here is an example how you can do it:

```yaml
hooksGeneral:
  env:
  - name: SOME_VAR
    value: "some value"
  - name: SOME_VAR_FROM_SECRET
    valueFrom:
      secretKeyRef:
        name: some_secret
        key: some_key
```
