### ISSUE TITLE
CronJob lifecycle yaml error

### ISSUE THREAD

**Issue by Tri0L** [nixys/nxs-universal-chart#40]
Hello.

Looks that lifecycle sections generates wrong yaml. Sections preStop/postStart must be inside lifecycle.

Example:
```
cronJobs:
  profiles:
    schedule: "00 05 * * *"
    containers:
      - name: test
        command: "mycommand"
        lifecycle:
          postStart:
            exec:
              command: ["post start command"]
          preStop:
            exec:
              command: ["pre stop command"]
```

Result: 
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-release-profiles
  namespace: "default"
  labels:
    app.kubernetes.io/name: test-release
    app.kubernetes.io/instance: test-release
    helm.sh/chart: universal-chart-2.1.4
    app.kubernetes.io/managed-by: Helm
  annotations:    
spec:
  schedule: "00 05 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
          annotations:
        spec:
          affinity:
            nodeAffinity:
              {}
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: test-release
                      app.kubernetes.io/instance: test-release
                  namespaces:
                  - "default"
                  topologyKey: kubernetes.io/hostname
                weight: 1
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: test-release
                      app.kubernetes.io/instance: test-release
                  namespaces:
                  - "default"
                  topologyKey: kubernetes.io/hostname
                weight: 1
          
          containers:
          - name: test
            image: nginx:latest
            imagePullPolicy: IfNotPresent
            command: ["mycommand"]                        
            lifecycle:    <<<======================= looks wrong
            postStart:
              exec:
                command:
                - post start command
            preStop:
              exec:
                command:
                - pre stop command
            volumeMounts:
            
              []
          volumes:          
            []
          restartPolicy: Never

```
