### ISSUE TITLE
Add volumes type - emptyDir

### ISSUE THREAD

**Issue by abix5** [nixys/nxs-universal-chart#42]
Quite strange, you have an initContainer, but no volumes with the emptyDir type. Please consider adding it.

```yaml
volumes:
  - type: emptyDir
     name: app
     sizeLimit: 500Mi
     medium: Memory

...

volumes:
  - type: emptyDir
     name: app
```

**Comment by randreev1321** [comment]
Hi, @abix5.

You don't need to use typed volume if you need emptyDir. Just use extraVolumes.

```yaml
extraVolumes:
  - name: cache
    emptyDir: {}
  - name: cache-limited
    emptyDir:
      sizeLimit: 500Mi
      medium: Memory
```

**Comment by GRomR1** [comment]
btw why not to add this option

```
    volumes:
    - name: uuid
      type: emptyDir
      # sizeLimit: 1Mi
      # medium: Memory
```

see MR #46
