### ISSUE TITLE
ConfigMaps file as executable script

### ISSUE THREAD

**Issue by kiper-prog** [nixys/nxs-universal-chart#58]
Hello, I suggest adding the configurable parameter `defaultMode` to ConfigMaps volumes.
This is necessary in order to be able to add scripts directly to the ConfigMap itself.
Currently, ConfigMaps are mounted with the following default permissions:

```yaml
volumes:
  - name: configs
    configMap:
      name: configs
      items:
      - key: main
        path: main.conf
      defaultMode: 420
```

This does not allow making the ConfigMap executable.

You can find more detailed information in the following links:
https://stackoverflow.com/questions/73365727/mounting-a-configmap-as-a-volume-in-kubernetes-how-do-i-calculate-the-value-of
https://itnext.io/kubernetes-tips-using-scripts-inside-configmaps-9df03e17ac35

**Comment by artemdanielyan** [comment]
Hello, thanks for your suggestion. I will implement it in upcoming release

**Comment by artemdanielyan** [comment]
Hello again! Just checked and it was implemented before by mode directive, you can try something like this:
```   
volumes:
    - name: ex-file
      type: configMap
      items:
      - key: exe
        mode: 0511
        path: exe
```
After templating it will look like this
```
          volumes:
          - name: ex-file
            configMap:
              name: ex-file
              items:
              - key: exe
                mode: 329
                path: exe
```
also you can specify mode with octal:
```   
volumes:
    - name: ex-file
      type: configMap
      items:
      - key: exe
        mode: 329
        path: exe
```

If defaultMode is still needed, please let me know.
