### ISSUE TITLE
Feature: Add template for SealedSecret

### ISSUE THREAD

**Issue by mlepeshkin** [nixys/nxs-universal-chart#77]
It would be awesome to add support for SealedSecrets (templates and helpers) so we can use them just like unencrypted secrets in the current chart version.

Here’s what it could look like in values.yaml:

```YAML
sealedSecrets:
  my-secret:
    encryptedData:
      FOO: "encryptedbar"
```

The template should then create a SealedSecret object using this definition.

We’re planning to add this to our project, and I’m happy to put together a PR to get this feature in.

**Comment by webchi** [comment]
merged https://github.com/nixys/nxs-universal-chart/pull/78

**Comment by webchi** [comment]
@mlepeshkin Hi! I have an error when trying to use more then one secret in the list:
```
sealedSecrets:
  secrets:
    encryptedData:
      APP_KEY: "AgBq8HvylIF7R+...I35H1ZE="
  regcred:
    annotations: 
      sealedsecrets.bitnami.com/cluster-wide: "true"    
    encryptedData:
      .dockerconfigjson: "AgDgc11XN1P9...vcjnoHWcLf4="
```
Error:
```
Error: YAML parse error on universal-chart/templates/secret.yml: error converting YAML to JSON: yaml: line 32: could not find expected ':'
```
Rendered yaml seems broken on annotations and end of a file
```
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
spec:
  encryptedData:
    .dockerconfigjson: AgDgc11XN1P9...vcjnoHWcLf4=
  template:
    metadata:
      name: doc-regcred
      labels:
        app.kubernetes.io/name: doc
        app.kubernetes.io/instance: doc
        helm.sh/chart: universal-chart-2.8.2
        app.kubernetes.io/managed-by: Helm
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"---
apiVersion: bitnami.com/v1alpha1                     ^---- here it is
kind: SealedSecret
```
