### ISSUE TITLE
Issues with rendering this chart on argocd?

### ISSUE THREAD

**Issue by GlacierWalrus** [nixys/nxs-universal-chart#85]
Hi, I use the chart in my argocd apps a lot and it usually works just fine.

I'm trying to use it to deploy a single secret in argocd, but argocd doesn't render any manifests for it, I installed the same version it uses locally (`version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}`) and I get the output I expect.

My app manifests looks something like this

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mySecrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-ns
    server: https://kubernetes.default.svc
  project: myProject
  source:
    repoURL: https://registry.nixys.io/chartrepo/public
    targetRevision: 2.8.3
    helm:
      releaseName: mySecrets
      valuesObject:
        secrets:
          secretA:
            data:
              foo: bar
```

I render it successfully on my machine with

```
helm template nixys/nxs-universal-chart  --namespace my-ns --version 2.8.3 -f (yq '.spec.source.helm.valuesObject' templates/secrets.yaml | psub)
```
and I get the output I expect.

No unusual logs or errors from argo, the app shows up as synced, just no resources.

Do you know of any weirdness with argocd and this chart?
