### ISSUE TITLE
`Error converting YAML to JSON` when trying to use wildcard as hostname: `*.example.com`

### ISSUE THREAD

**Issue by radekbenkel** [nixys/nxs-universal-chart#86]
With such `demo.yaml`: 

```yaml
ingresses:
  "subdomain":
    annotations:
      kubernetes.io/ingress.class: nginx-ingress
    hosts:
      - hostname: "*.example.com"
        paths:
          - path: /some/path/that/uses/subdomain
            servicePort: 3000
```

and latest `main` revision of the repository (`75bd992`) it produces error: 

```
$ helm template ../../oss/nxs-universal-chart --values demo.yaml --debug
install.go:225: 2025-05-30 10:10:51.601931 +0200 CEST m=+0.021609417 [debug] Original chart version: ""
install.go:242: 2025-05-30 10:10:51.602693 +0200 CEST m=+0.022370751 [debug] CHART PATH: /Users/radek/Code/oss/nxs-universal-chart

---
# Source: universal-chart/templates/ingress.yml

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-subdomain
  namespace: "default"
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name

    helm.sh/chart: universal-chart-2.8.1
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
spec:
  rules:
  - host: *.example.com
    http:
      paths:
      - path: /some/path/that/uses/subdomain
        pathType: Prefix
        backend:
          service:
            name: release-name
            port:
              number: 3000
Error: YAML parse error on universal-chart/templates/ingress.yml: error converting YAML to JSON: yaml: line 16: did not find expected alphabetic or numeric character
helm.go:92: 2025-05-30 10:10:51.608742 +0200 CEST m=+0.028419834 [debug] error converting YAML to JSON: yaml: line 16: did not find expected alphabetic or numeric character
YAML parse error on universal-chart/templates/ingress.yml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:152
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:104
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:172
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:316
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:317
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:95
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.9.1/command.go:1015
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.9.1/command.go:1148
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.9.1/command.go:1071
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:91
runtime.main
	runtime/proc.go:283
runtime.goexit
	runtime/asm_arm64.s:1223
```

When changing `hostname` to `a.example.com` it works correctly. 

I think it's the matter of adding `| quote` (or more complicated code including `hasPrefix` if `host` should be quoted only if necessary and not always).  https://github.com/nixys/nxs-universal-chart/blob/75bd9925e738d4deea75629b7981be63b16314cf/templates/helpers/_tplvalues.tpl#L3

**Comment by GlacierWalrus** [comment]
I'm not a maintainer, but the issue isn't with the chart- it's that you're ultimately outputting invalid yaml. You can invoke it the following ways to get your desired output:

1. Pass your own template string to do what you like:
```
helm template nixys/universal-chart -f - <<EOF
ingresses:
  "subdomain":
    annotations:
      kubernetes.io/ingress.class: nginx-ingress
    hosts:
      - hostname: "{{ printf \"*.example.com\" | quote }}"
        paths:
          - path: /some/path/that/uses/subdomain
            servicePort: 3000
EOF

---
# Source: universal-chart/templates/ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-subdomain
  namespace: "platform"
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name

    helm.sh/chart: universal-chart-2.8.3
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
spec:
  rules:
  - host: "*.example.com"
    http:
      paths:
      - path: /some/path/that/uses/subdomain
        pathType: Prefix
        backend:
          service:
            name: release-name
            port:
              number: 3000
```

2: Inhibit templating in this chart (using single quotes rather than double) and explicitly escape your asterisk, to appease the YAML gods.

```
helm template nixys/universal-chart -f - <<EOF
ingresses:
  "subdomain":
    annotations:
      kubernetes.io/ingress.class: nginx-ingress
    hosts:
      - hostname: '\\*.example.com'
        paths:
          - path: /some/path/that/uses/subdomain
            servicePort: 3000
EOF
---
# Source: universal-chart/templates/ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-subdomain
  namespace: "platform"
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name

    helm.sh/chart: universal-chart-2.8.3
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
spec:
  rules:
  - host: \*.example.com
    http:
      paths:
      - path: /some/path/that/uses/subdomain
        pathType: Prefix
        backend:
          service:
            name: release-name
            port:
              number: 3000
```

Hope that helps you.

**Comment by radekbenkel** [comment]
@GlacierWalrus thanks, that was helpful! I used the first approach 🙏 

But I'm still wondering whether this is an issue or not. I know I'm outputting invalid YAML. Thing is, my INPUT to this chart is **valid** YAML - like below

```yaml
ingresses:
  subdomain:
    hosts:
      - hostname: "*.example.com"
        paths:
          - path: /some/path/that/uses/subdomain
            servicePort: 3000
```

So, a tool which accepts valid YAML produces invalid YAML in some cases. 

But in the end, it's the maintainer's decision whether it's a bug or not, I won't mind if this issue will be closed as "works-as-intended" :)
